export interface Product { id: string; title: string; price: number; rating: number; description: string; image: string; brand: string; category: string; subcategory: string; stock: number; isHot: boolean; isNew: boolean; discount: number; }

export const Products: Product[] = [
  {
    "id": "p-101",
    "title": "Essential Lipstick",
    "price": 30.14,
    "rating": 4.8,
    "description": "Essential Lipstick featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/essential-lipstick-eyeliner/800/800",
    "brand": "Huda Beauty",
    "category": "makeup",
    "subcategory": "eyeliner",
    "stock": 29,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-102",
    "title": "Cloud Eye Cream",
    "price": 18.7,
    "rating": 4.6,
    "description": "Cloud Eye Cream featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/cloud-eye-cream-sunscreen/800/800",
    "brand": "Schwarzkopf",
    "category": "skincare",
    "subcategory": "sunscreen",
    "stock": 75,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-103",
    "title": "Nourish Hair Color",
    "price": 26.31,
    "rating": 4.1,
    "description": "Nourish Hair Color featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/nourish-hair-color-conditioner/800/800",
    "brand": "NARS",
    "category": "hair",
    "subcategory": "conditioner",
    "stock": 97,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-104",
    "title": "Velvet Sunscreen",
    "price": 14.15,
    "rating": 5.0,
    "description": "Velvet Sunscreen featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/velvet-sunscreen-wash/800/800",
    "brand": "Rare Beauty",
    "category": "body",
    "subcategory": "wash",
    "stock": 5,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-105",
    "title": "Studio Gift Set",
    "price": 37.89,
    "rating": 4.0,
    "description": "Studio Gift Set featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/studio-gift-set-men/800/800",
    "brand": "Rare Beauty",
    "category": "fragrance",
    "subcategory": "men",
    "stock": 18,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-106",
    "title": "Silky Nail File Set",
    "price": 16.92,
    "rating": 4.9,
    "description": "Silky Nail File Set featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/silky-nail-file-set-gel-acrylic/800/800",
    "brand": "Sephora Collection",
    "category": "nails",
    "subcategory": "gel-acrylic",
    "stock": 108,
    "isHot": true,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-107",
    "title": "Soft LED Mirror",
    "price": 41.28,
    "rating": 4.5,
    "description": "Soft LED Mirror featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/soft-led-mirror-tweezers/800/800",
    "brand": "MAC",
    "category": "tools",
    "subcategory": "tweezers",
    "stock": 37,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-108",
    "title": "Hydra Shaving Cream",
    "price": 21.46,
    "rating": 4.9,
    "description": "Hydra Shaving Cream featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/hydra-shaving-cream-shaving/800/800",
    "brand": "GlowCart",
    "category": "men",
    "subcategory": "shaving",
    "stock": 24,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-109",
    "title": "Pure Fragrance Box",
    "price": 39.28,
    "rating": 4.0,
    "description": "Pure Fragrance Box featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/pure-fragrance-box-hair-set/800/800",
    "brand": "Laneige",
    "category": "gifts",
    "subcategory": "hair-set",
    "stock": 15,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-110",
    "title": "Velvet Brow Pencil",
    "price": 27.23,
    "rating": 4.1,
    "description": "Velvet Brow Pencil featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/velvet-brow-pencil-concealer/800/800",
    "brand": "Olaplex",
    "category": "makeup",
    "subcategory": "concealer",
    "stock": 102,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-111",
    "title": "Dream Exfoliator",
    "price": 21.36,
    "rating": 4.6,
    "description": "Dream Exfoliator featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/dream-exfoliator-cleanser/800/800",
    "brand": "Rare Beauty",
    "category": "skincare",
    "subcategory": "cleanser",
    "stock": 75,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-112",
    "title": "Crystal Hair Mask",
    "price": 9.64,
    "rating": 4.1,
    "description": "Crystal Hair Mask featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/crystal-hair-mask-conditioner/800/800",
    "brand": "Sephora Collection",
    "category": "hair",
    "subcategory": "conditioner",
    "stock": 34,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-113",
    "title": "Crystal Body Cream",
    "price": 18.47,
    "rating": 3.9,
    "description": "Crystal Body Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/crystal-body-cream-cream/800/800",
    "brand": "GlowCart",
    "category": "body",
    "subcategory": "cream",
    "stock": 89,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-114",
    "title": "Cloud Body Mist",
    "price": 70.52,
    "rating": 4.3,
    "description": "Cloud Body Mist featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/cloud-body-mist-oil/800/800",
    "brand": "Laneige",
    "category": "fragrance",
    "subcategory": "oil",
    "stock": 58,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-115",
    "title": "Velvet Cuticle Oil",
    "price": 11.61,
    "rating": 4.3,
    "description": "Velvet Cuticle Oil featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/velvet-cuticle-oil-care/800/800",
    "brand": "MAC",
    "category": "nails",
    "subcategory": "care",
    "stock": 78,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-116",
    "title": "Fresh Makeup Bag",
    "price": 36.44,
    "rating": 4.3,
    "description": "Fresh Makeup Bag featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/fresh-makeup-bag-sponge/800/800",
    "brand": "Maybelline",
    "category": "tools",
    "subcategory": "sponge",
    "stock": 87,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-117",
    "title": "Air Shaving Cream",
    "price": 42.96,
    "rating": 4.5,
    "description": "Air Shaving Cream featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/air-shaving-cream-face-wash/800/800",
    "brand": "The Ordinary",
    "category": "men",
    "subcategory": "face-wash",
    "stock": 47,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-118",
    "title": "Luxe Fragrance Box",
    "price": 18.3,
    "rating": 4.8,
    "description": "Luxe Fragrance Box featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/luxe-fragrance-box-makeup-set/800/800",
    "brand": "TRESemm\u00e9",
    "category": "gifts",
    "subcategory": "makeup-set",
    "stock": 78,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-119",
    "title": "Matte Setting Powder",
    "price": 25.14,
    "rating": 4.2,
    "description": "Matte Setting Powder featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/matte-setting-powder-concealer/800/800",
    "brand": "Laneige",
    "category": "makeup",
    "subcategory": "concealer",
    "stock": 92,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-120",
    "title": "Luxe Face Mask",
    "price": 38.23,
    "rating": 4.4,
    "description": "Luxe Face Mask featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/luxe-face-mask-acne/800/800",
    "brand": "CeraVe",
    "category": "skincare",
    "subcategory": "acne",
    "stock": 62,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-121",
    "title": "Perfect Conditioner",
    "price": 8.01,
    "rating": 4.6,
    "description": "Perfect Conditioner featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/perfect-conditioner-shampoo/800/800",
    "brand": "NARS",
    "category": "hair",
    "subcategory": "shampoo",
    "stock": 115,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-122",
    "title": "Soft Deodorant",
    "price": 23.41,
    "rating": 4.8,
    "description": "Soft Deodorant featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/soft-deodorant-wash/800/800",
    "brand": "Maybelline",
    "category": "body",
    "subcategory": "wash",
    "stock": 83,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-123",
    "title": "Fresh Eau de Toilette",
    "price": 36.05,
    "rating": 4.1,
    "description": "Fresh Eau de Toilette featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/fresh-eau-de-toilette-women/800/800",
    "brand": "Garnier",
    "category": "fragrance",
    "subcategory": "women",
    "stock": 34,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-124",
    "title": "Cloud Nail File Set",
    "price": 5.63,
    "rating": 5.0,
    "description": "Cloud Nail File Set featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/cloud-nail-file-set-care/800/800",
    "brand": "Fenty Beauty",
    "category": "nails",
    "subcategory": "care",
    "stock": 45,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-125",
    "title": "Radiant Makeup Bag",
    "price": 15.08,
    "rating": 4.5,
    "description": "Radiant Makeup Bag featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/radiant-makeup-bag-tweezers/800/800",
    "brand": "Huda Beauty",
    "category": "tools",
    "subcategory": "tweezers",
    "stock": 25,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-126",
    "title": "Cloud Face Wash",
    "price": 16.95,
    "rating": 4.5,
    "description": "Cloud Face Wash featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/cloud-face-wash-beard/800/800",
    "brand": "Rare Beauty",
    "category": "men",
    "subcategory": "beard",
    "stock": 72,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-127",
    "title": "Air Skincare Kit",
    "price": 49.31,
    "rating": 4.4,
    "description": "Air Skincare Kit featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/air-skincare-kit-hair-set/800/800",
    "brand": "Huda Beauty",
    "category": "gifts",
    "subcategory": "hair-set",
    "stock": 89,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-128",
    "title": "Crystal Setting Spray",
    "price": 24.05,
    "rating": 4.3,
    "description": "Crystal Setting Spray featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/crystal-setting-spray-setting/800/800",
    "brand": "Laneige",
    "category": "makeup",
    "subcategory": "setting",
    "stock": 10,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-129",
    "title": "Radiant Eye Cream",
    "price": 31.18,
    "rating": 4.0,
    "description": "Radiant Eye Cream featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/radiant-eye-cream-mask/800/800",
    "brand": "L'Oreal",
    "category": "skincare",
    "subcategory": "mask",
    "stock": 67,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-130",
    "title": "Hydra Shampoo",
    "price": 17.19,
    "rating": 4.1,
    "description": "Hydra Shampoo featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/hydra-shampoo-mask/800/800",
    "brand": "L'Oreal",
    "category": "hair",
    "subcategory": "mask",
    "stock": 63,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-131",
    "title": "Silky Hand Cream",
    "price": 23.88,
    "rating": 4.1,
    "description": "Silky Hand Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/silky-hand-cream-cream/800/800",
    "brand": "Pantene",
    "category": "body",
    "subcategory": "cream",
    "stock": 74,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-132",
    "title": "Pure Eau de Toilette",
    "price": 75.37,
    "rating": 4.9,
    "description": "Pure Eau de Toilette featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/pure-eau-de-toilette-body-mist/800/800",
    "brand": "NARS",
    "category": "fragrance",
    "subcategory": "body-mist",
    "stock": 25,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-133",
    "title": "Dream Nail Care Kit",
    "price": 6.46,
    "rating": 4.9,
    "description": "Dream Nail Care Kit featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/dream-nail-care-kit-polish/800/800",
    "brand": "Maybelline",
    "category": "nails",
    "subcategory": "polish",
    "stock": 76,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-134",
    "title": "Silky Beauty Sponge",
    "price": 49.15,
    "rating": 4.1,
    "description": "Silky Beauty Sponge featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/silky-beauty-sponge-bags/800/800",
    "brand": "Huda Beauty",
    "category": "tools",
    "subcategory": "bags",
    "stock": 98,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-135",
    "title": "Silky Men's Perfume",
    "price": 28.63,
    "rating": 4.8,
    "description": "Silky Men's Perfume featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/silky-mens-perfume-face-wash/800/800",
    "brand": "Olaplex",
    "category": "men",
    "subcategory": "face-wash",
    "stock": 18,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-136",
    "title": "Silky Fragrance Box",
    "price": 51.99,
    "rating": 4.0,
    "description": "Silky Fragrance Box featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/silky-fragrance-box-hair-set/800/800",
    "brand": "Laneige",
    "category": "gifts",
    "subcategory": "hair-set",
    "stock": 19,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-137",
    "title": "Air Foundation",
    "price": 12.62,
    "rating": 4.7,
    "description": "Air Foundation featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/air-foundation-eyeliner/800/800",
    "brand": "Fenty Beauty",
    "category": "makeup",
    "subcategory": "eyeliner",
    "stock": 38,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-138",
    "title": "Dream Cleanser",
    "price": 29.18,
    "rating": 4.7,
    "description": "Dream Cleanser featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/dream-cleanser-moisturizer/800/800",
    "brand": "GlowCart",
    "category": "skincare",
    "subcategory": "moisturizer",
    "stock": 108,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-139",
    "title": "Dream Hair Serum",
    "price": 7.93,
    "rating": 4.3,
    "description": "Dream Hair Serum featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/dream-hair-serum-oil/800/800",
    "brand": "NARS",
    "category": "hair",
    "subcategory": "oil",
    "stock": 76,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-140",
    "title": "Soft Deodorant",
    "price": 28.04,
    "rating": 3.9,
    "description": "Soft Deodorant featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/soft-deodorant-sun-care/800/800",
    "brand": "Dior",
    "category": "body",
    "subcategory": "sun-care",
    "stock": 77,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-141",
    "title": "Glow Eau de Toilette",
    "price": 32.84,
    "rating": 4.6,
    "description": "Glow Eau de Toilette featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/glow-eau-de-toilette-men/800/800",
    "brand": "Garnier",
    "category": "fragrance",
    "subcategory": "men",
    "stock": 70,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-142",
    "title": "Perfect Nail File Set",
    "price": 13.03,
    "rating": 4.6,
    "description": "Perfect Nail File Set featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/perfect-nail-file-set-gel-acrylic/800/800",
    "brand": "Laneige",
    "category": "nails",
    "subcategory": "gel-acrylic",
    "stock": 78,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-143",
    "title": "Crystal Brush Set",
    "price": 34.97,
    "rating": 5.0,
    "description": "Crystal Brush Set featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/crystal-brush-set-curler/800/800",
    "brand": "Kiehl's",
    "category": "tools",
    "subcategory": "curler",
    "stock": 88,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-144",
    "title": "Cloud Men's Perfume",
    "price": 50.2,
    "rating": 4.0,
    "description": "Cloud Men's Perfume featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/cloud-mens-perfume-perfume/800/800",
    "brand": "Sephora Collection",
    "category": "men",
    "subcategory": "perfume",
    "stock": 118,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-145",
    "title": "Shine Makeup Gift Set",
    "price": 70.46,
    "rating": 4.2,
    "description": "Shine Makeup Gift Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/shine-makeup-gift-set-makeup-set/800/800",
    "brand": "Schwarzkopf",
    "category": "gifts",
    "subcategory": "makeup-set",
    "stock": 5,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-146",
    "title": "Matte Concealer",
    "price": 30.72,
    "rating": 4.2,
    "description": "Matte Concealer featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/matte-concealer-lipstick/800/800",
    "brand": "Dior",
    "category": "makeup",
    "subcategory": "lipstick",
    "stock": 54,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-147",
    "title": "Glow Eye Cream",
    "price": 9.61,
    "rating": 4.2,
    "description": "Glow Eye Cream featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/glow-eye-cream-acne/800/800",
    "brand": "Schwarzkopf",
    "category": "skincare",
    "subcategory": "acne",
    "stock": 115,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-148",
    "title": "Revive Hair Mask",
    "price": 27.03,
    "rating": 4.7,
    "description": "Revive Hair Mask featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/revive-hair-mask-color/800/800",
    "brand": "Pantene",
    "category": "hair",
    "subcategory": "color",
    "stock": 110,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-149",
    "title": "Revive Sunscreen",
    "price": 22.61,
    "rating": 4.4,
    "description": "Revive Sunscreen featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/revive-sunscreen-cream/800/800",
    "brand": "Huda Beauty",
    "category": "body",
    "subcategory": "cream",
    "stock": 34,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-150",
    "title": "Nourish Body Mist",
    "price": 69.16,
    "rating": 4.8,
    "description": "Nourish Body Mist featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/nourish-body-mist-oil/800/800",
    "brand": "Schwarzkopf",
    "category": "fragrance",
    "subcategory": "oil",
    "stock": 34,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-151",
    "title": "Radiant Nail Care Kit",
    "price": 15.68,
    "rating": 4.7,
    "description": "Radiant Nail Care Kit featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/radiant-nail-care-kit-polish/800/800",
    "brand": "L'Oreal",
    "category": "nails",
    "subcategory": "polish",
    "stock": 104,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-152",
    "title": "Perfect Beauty Sponge",
    "price": 6.05,
    "rating": 4.3,
    "description": "Perfect Beauty Sponge featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/perfect-beauty-sponge-sponge/800/800",
    "brand": "Pantene",
    "category": "tools",
    "subcategory": "sponge",
    "stock": 36,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-153",
    "title": "Air Aftershave Balm",
    "price": 23.64,
    "rating": 4.3,
    "description": "Air Aftershave Balm featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/air-aftershave-balm-face-wash/800/800",
    "brand": "Pantene",
    "category": "men",
    "subcategory": "face-wash",
    "stock": 20,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-154",
    "title": "Silky Hair Care Set",
    "price": 22.46,
    "rating": 4.7,
    "description": "Silky Hair Care Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/silky-hair-care-set-hair-set/800/800",
    "brand": "NYX",
    "category": "gifts",
    "subcategory": "hair-set",
    "stock": 69,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-155",
    "title": "Soft Eyeshadow Palette",
    "price": 33.01,
    "rating": 4.0,
    "description": "Soft Eyeshadow Palette featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/soft-eyeshadow-palette-eyeshadow/800/800",
    "brand": "Dior",
    "category": "makeup",
    "subcategory": "eyeshadow",
    "stock": 106,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-156",
    "title": "Radiant Cleanser",
    "price": 9.47,
    "rating": 4.3,
    "description": "Radiant Cleanser featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/radiant-cleanser-cleanser/800/800",
    "brand": "Pantene",
    "category": "skincare",
    "subcategory": "cleanser",
    "stock": 58,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-157",
    "title": "Revive Conditioner",
    "price": 18.76,
    "rating": 4.0,
    "description": "Revive Conditioner featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/revive-conditioner-mask/800/800",
    "brand": "Dior",
    "category": "hair",
    "subcategory": "mask",
    "stock": 7,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-158",
    "title": "Matte Hand Cream",
    "price": 29.04,
    "rating": 4.2,
    "description": "Matte Hand Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/matte-hand-cream-cream/800/800",
    "brand": "TRESemm\u00e9",
    "category": "body",
    "subcategory": "cream",
    "stock": 47,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-159",
    "title": "Revive Gift Set",
    "price": 36.96,
    "rating": 4.7,
    "description": "Revive Gift Set featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/revive-gift-set-unisex/800/800",
    "brand": "Fenty Beauty",
    "category": "fragrance",
    "subcategory": "unisex",
    "stock": 8,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-160",
    "title": "Radiant Nail Care Kit",
    "price": 16.11,
    "rating": 4.6,
    "description": "Radiant Nail Care Kit featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/radiant-nail-care-kit-tools/800/800",
    "brand": "CeraVe",
    "category": "nails",
    "subcategory": "tools",
    "stock": 42,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-161",
    "title": "Prime Tweezers",
    "price": 30.34,
    "rating": 4.3,
    "description": "Prime Tweezers featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/prime-tweezers-curler/800/800",
    "brand": "L'Oreal",
    "category": "tools",
    "subcategory": "curler",
    "stock": 86,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-162",
    "title": "Pure Beard Oil",
    "price": 38.79,
    "rating": 4.5,
    "description": "Pure Beard Oil featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/pure-beard-oil-face-wash/800/800",
    "brand": "L'Oreal",
    "category": "men",
    "subcategory": "face-wash",
    "stock": 57,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-163",
    "title": "Calm Makeup Gift Set",
    "price": 45.31,
    "rating": 4.2,
    "description": "Calm Makeup Gift Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/calm-makeup-gift-set-makeup-set/800/800",
    "brand": "Olaplex",
    "category": "gifts",
    "subcategory": "makeup-set",
    "stock": 71,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-164",
    "title": "Dream Foundation",
    "price": 19.52,
    "rating": 4.2,
    "description": "Dream Foundation featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/dream-foundation-concealer/800/800",
    "brand": "L'Oreal",
    "category": "makeup",
    "subcategory": "concealer",
    "stock": 90,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-165",
    "title": "Luxe Serum",
    "price": 23.32,
    "rating": 4.2,
    "description": "Luxe Serum featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/luxe-serum-acne/800/800",
    "brand": "Garnier",
    "category": "skincare",
    "subcategory": "acne",
    "stock": 119,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-166",
    "title": "Calm Hair Color",
    "price": 23.02,
    "rating": 4.0,
    "description": "Calm Hair Color featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/calm-hair-color-color/800/800",
    "brand": "Kiehl's",
    "category": "hair",
    "subcategory": "color",
    "stock": 33,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-167",
    "title": "Soft Body Scrub",
    "price": 27.91,
    "rating": 4.0,
    "description": "Soft Body Scrub featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/soft-body-scrub-deodorant/800/800",
    "brand": "Pantene",
    "category": "body",
    "subcategory": "deodorant",
    "stock": 108,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-168",
    "title": "Radiant Eau de Toilette",
    "price": 84.19,
    "rating": 4.8,
    "description": "Radiant Eau de Toilette featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/radiant-eau-de-toilette-men/800/800",
    "brand": "L'Oreal",
    "category": "fragrance",
    "subcategory": "men",
    "stock": 21,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-169",
    "title": "Luxe Nail Polish",
    "price": 21.58,
    "rating": 4.2,
    "description": "Luxe Nail Polish featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/luxe-nail-polish-polish/800/800",
    "brand": "GlowCart",
    "category": "nails",
    "subcategory": "polish",
    "stock": 66,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-170",
    "title": "Ultra Brush Set",
    "price": 6.57,
    "rating": 4.4,
    "description": "Ultra Brush Set featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/ultra-brush-set-mirrors/800/800",
    "brand": "Garnier",
    "category": "tools",
    "subcategory": "mirrors",
    "stock": 61,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-171",
    "title": "Calm Aftershave Balm",
    "price": 53.78,
    "rating": 4.7,
    "description": "Calm Aftershave Balm featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/calm-aftershave-balm-shaving/800/800",
    "brand": "Dior",
    "category": "men",
    "subcategory": "shaving",
    "stock": 86,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-172",
    "title": "Fresh Skincare Kit",
    "price": 47.44,
    "rating": 4.8,
    "description": "Fresh Skincare Kit featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/fresh-skincare-kit-skincare-set/800/800",
    "brand": "The Ordinary",
    "category": "gifts",
    "subcategory": "skincare-set",
    "stock": 54,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-173",
    "title": "Prime Primer",
    "price": 32.46,
    "rating": 4.9,
    "description": "Prime Primer featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/prime-primer-foundation/800/800",
    "brand": "L'Oreal",
    "category": "makeup",
    "subcategory": "foundation",
    "stock": 82,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-174",
    "title": "Cloud Eye Cream",
    "price": 34.88,
    "rating": 5.0,
    "description": "Cloud Eye Cream featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/cloud-eye-cream-cleanser/800/800",
    "brand": "Kiehl's",
    "category": "skincare",
    "subcategory": "cleanser",
    "stock": 88,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-175",
    "title": "Velvet Hair Mask",
    "price": 11.01,
    "rating": 4.3,
    "description": "Velvet Hair Mask featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/velvet-hair-mask-color/800/800",
    "brand": "L'Oreal",
    "category": "hair",
    "subcategory": "color",
    "stock": 29,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-176",
    "title": "Air Sunscreen",
    "price": 16.1,
    "rating": 4.3,
    "description": "Air Sunscreen featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/air-sunscreen-cream/800/800",
    "brand": "Fenty Beauty",
    "category": "body",
    "subcategory": "cream",
    "stock": 58,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-177",
    "title": "Dream Eau de Parfum",
    "price": 56.64,
    "rating": 3.9,
    "description": "Dream Eau de Parfum featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/dream-eau-de-parfum-men/800/800",
    "brand": "NYX",
    "category": "fragrance",
    "subcategory": "men",
    "stock": 64,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-178",
    "title": "Studio Nail File Set",
    "price": 13.94,
    "rating": 4.8,
    "description": "Studio Nail File Set featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/studio-nail-file-set-polish/800/800",
    "brand": "NYX",
    "category": "nails",
    "subcategory": "polish",
    "stock": 15,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-179",
    "title": "Calm Brush Set",
    "price": 49.18,
    "rating": 4.8,
    "description": "Calm Brush Set featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/calm-brush-set-bags/800/800",
    "brand": "Sephora Collection",
    "category": "tools",
    "subcategory": "bags",
    "stock": 111,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-180",
    "title": "Luxe Men's Perfume",
    "price": 22.51,
    "rating": 4.0,
    "description": "Luxe Men's Perfume featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/luxe-mens-perfume-shampoo/800/800",
    "brand": "The Ordinary",
    "category": "men",
    "subcategory": "shampoo",
    "stock": 67,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-181",
    "title": "Glow Hair Care Set",
    "price": 55.79,
    "rating": 4.8,
    "description": "Glow Hair Care Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/glow-hair-care-set-makeup-set/800/800",
    "brand": "Kiehl's",
    "category": "gifts",
    "subcategory": "makeup-set",
    "stock": 49,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-182",
    "title": "Prime Highlighter",
    "price": 17.53,
    "rating": 4.1,
    "description": "Prime Highlighter featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/prime-highlighter-eyeshadow/800/800",
    "brand": "Maybelline",
    "category": "makeup",
    "subcategory": "eyeshadow",
    "stock": 18,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-183",
    "title": "Essential Spot Treatment",
    "price": 16.36,
    "rating": 4.1,
    "description": "Essential Spot Treatment featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/essential-spot-treatment-exfoliator/800/800",
    "brand": "The Ordinary",
    "category": "skincare",
    "subcategory": "exfoliator",
    "stock": 109,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-184",
    "title": "Nourish Conditioner",
    "price": 32.98,
    "rating": 4.7,
    "description": "Nourish Conditioner featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/nourish-conditioner-color/800/800",
    "brand": "Laneige",
    "category": "hair",
    "subcategory": "color",
    "stock": 113,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-185",
    "title": "Silky Body Lotion",
    "price": 9.44,
    "rating": 4.5,
    "description": "Silky Body Lotion featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/silky-body-lotion-hand-foot/800/800",
    "brand": "GlowCart",
    "category": "body",
    "subcategory": "hand-foot",
    "stock": 29,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-186",
    "title": "Nourish Eau de Toilette",
    "price": 40.08,
    "rating": 4.9,
    "description": "Nourish Eau de Toilette featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/nourish-eau-de-toilette-body-mist/800/800",
    "brand": "Sephora Collection",
    "category": "fragrance",
    "subcategory": "body-mist",
    "stock": 111,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-187",
    "title": "Calm Nail Polish",
    "price": 9.66,
    "rating": 4.9,
    "description": "Calm Nail Polish featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/calm-nail-polish-care/800/800",
    "brand": "The Ordinary",
    "category": "nails",
    "subcategory": "care",
    "stock": 106,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-188",
    "title": "Hydra LED Mirror",
    "price": 42.86,
    "rating": 4.9,
    "description": "Hydra LED Mirror featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/hydra-led-mirror-hair-brush/800/800",
    "brand": "Dior",
    "category": "tools",
    "subcategory": "hair-brush",
    "stock": 22,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-189",
    "title": "Brilliant Shaving Cream",
    "price": 22.46,
    "rating": 4.0,
    "description": "Brilliant Shaving Cream featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/brilliant-shaving-cream-aftershave/800/800",
    "brand": "Dior",
    "category": "men",
    "subcategory": "aftershave",
    "stock": 116,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-190",
    "title": "Brilliant Fragrance Box",
    "price": 58.4,
    "rating": 4.9,
    "description": "Brilliant Fragrance Box featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/brilliant-fragrance-box-hair-set/800/800",
    "brand": "Olaplex",
    "category": "gifts",
    "subcategory": "hair-set",
    "stock": 49,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-191",
    "title": "Calm Blush",
    "price": 11.16,
    "rating": 4.6,
    "description": "Calm Blush featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/calm-blush-blush/800/800",
    "brand": "TRESemm\u00e9",
    "category": "makeup",
    "subcategory": "blush",
    "stock": 52,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-192",
    "title": "Radiant Sunscreen",
    "price": 46.11,
    "rating": 4.1,
    "description": "Radiant Sunscreen featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/radiant-sunscreen-mask/800/800",
    "brand": "Pantene",
    "category": "skincare",
    "subcategory": "mask",
    "stock": 102,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-193",
    "title": "Revive Hair Spray",
    "price": 33.74,
    "rating": 4.9,
    "description": "Revive Hair Spray featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/revive-hair-spray-serum/800/800",
    "brand": "Olaplex",
    "category": "hair",
    "subcategory": "serum",
    "stock": 89,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-194",
    "title": "Prime Body Scrub",
    "price": 6.53,
    "rating": 4.7,
    "description": "Prime Body Scrub featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/prime-body-scrub-deodorant/800/800",
    "brand": "MAC",
    "category": "body",
    "subcategory": "deodorant",
    "stock": 103,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-195",
    "title": "Calm Perfume Oil",
    "price": 23.2,
    "rating": 4.6,
    "description": "Calm Perfume Oil featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/calm-perfume-oil-unisex/800/800",
    "brand": "Olaplex",
    "category": "fragrance",
    "subcategory": "unisex",
    "stock": 14,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-196",
    "title": "Soft Nail File Set",
    "price": 13.51,
    "rating": 5.0,
    "description": "Soft Nail File Set featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/soft-nail-file-set-tools/800/800",
    "brand": "Olaplex",
    "category": "nails",
    "subcategory": "tools",
    "stock": 111,
    "isHot": true,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-197",
    "title": "Soft Makeup Bag",
    "price": 36.58,
    "rating": 4.1,
    "description": "Soft Makeup Bag featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/soft-makeup-bag-hair-brush/800/800",
    "brand": "Rare Beauty",
    "category": "tools",
    "subcategory": "hair-brush",
    "stock": 79,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-198",
    "title": "Soft Men's Shampoo",
    "price": 22.83,
    "rating": 4.4,
    "description": "Soft Men's Shampoo featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/soft-mens-shampoo-perfume/800/800",
    "brand": "Huda Beauty",
    "category": "men",
    "subcategory": "perfume",
    "stock": 103,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-199",
    "title": "Calm Fragrance Box",
    "price": 69.71,
    "rating": 5.0,
    "description": "Calm Fragrance Box featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/calm-fragrance-box-skincare-set/800/800",
    "brand": "Garnier",
    "category": "gifts",
    "subcategory": "skincare-set",
    "stock": 36,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-200",
    "title": "Pure Highlighter",
    "price": 23.72,
    "rating": 4.5,
    "description": "Pure Highlighter featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/pure-highlighter-eyeliner/800/800",
    "brand": "Schwarzkopf",
    "category": "makeup",
    "subcategory": "eyeliner",
    "stock": 48,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-201",
    "title": "Fresh Face Mask",
    "price": 27.83,
    "rating": 4.9,
    "description": "Fresh Face Mask featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/fresh-face-mask-sunscreen/800/800",
    "brand": "Sephora Collection",
    "category": "skincare",
    "subcategory": "sunscreen",
    "stock": 115,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-202",
    "title": "Velvet Hair Spray",
    "price": 11.44,
    "rating": 4.1,
    "description": "Velvet Hair Spray featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/velvet-hair-spray-shampoo/800/800",
    "brand": "Garnier",
    "category": "hair",
    "subcategory": "shampoo",
    "stock": 56,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-203",
    "title": "Calm Body Cream",
    "price": 29.22,
    "rating": 4.3,
    "description": "Calm Body Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/calm-body-cream-lotion/800/800",
    "brand": "L'Oreal",
    "category": "body",
    "subcategory": "lotion",
    "stock": 77,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-204",
    "title": "Cloud Gift Set",
    "price": 36.78,
    "rating": 3.9,
    "description": "Cloud Gift Set featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/cloud-gift-set-gift-set/800/800",
    "brand": "MAC",
    "category": "fragrance",
    "subcategory": "gift-set",
    "stock": 45,
    "isHot": true,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-205",
    "title": "Dream Nail File Set",
    "price": 7.21,
    "rating": 4.7,
    "description": "Dream Nail File Set featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/dream-nail-file-set-care/800/800",
    "brand": "Dior",
    "category": "nails",
    "subcategory": "care",
    "stock": 89,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-206",
    "title": "Prime Lash Curler",
    "price": 35.73,
    "rating": 4.0,
    "description": "Prime Lash Curler featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/prime-lash-curler-tweezers/800/800",
    "brand": "Sephora Collection",
    "category": "tools",
    "subcategory": "tweezers",
    "stock": 45,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-207",
    "title": "Luxe Aftershave Balm",
    "price": 42.97,
    "rating": 3.9,
    "description": "Luxe Aftershave Balm featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/luxe-aftershave-balm-shaving/800/800",
    "brand": "Huda Beauty",
    "category": "men",
    "subcategory": "shaving",
    "stock": 85,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-208",
    "title": "Velvet Makeup Gift Set",
    "price": 86.5,
    "rating": 4.5,
    "description": "Velvet Makeup Gift Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/velvet-makeup-gift-set-fragrance-box/800/800",
    "brand": "L'Oreal",
    "category": "gifts",
    "subcategory": "fragrance-box",
    "stock": 118,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-209",
    "title": "Dream Mascara",
    "price": 27.88,
    "rating": 4.0,
    "description": "Dream Mascara featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/dream-mascara-foundation/800/800",
    "brand": "Huda Beauty",
    "category": "makeup",
    "subcategory": "foundation",
    "stock": 58,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-210",
    "title": "Brilliant Face Oil",
    "price": 21.8,
    "rating": 5.0,
    "description": "Brilliant Face Oil featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/brilliant-face-oil-cleanser/800/800",
    "brand": "NARS",
    "category": "skincare",
    "subcategory": "cleanser",
    "stock": 57,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-211",
    "title": "Glow Hair Serum",
    "price": 7.26,
    "rating": 4.8,
    "description": "Glow Hair Serum featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/glow-hair-serum-serum/800/800",
    "brand": "NYX",
    "category": "hair",
    "subcategory": "serum",
    "stock": 54,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-212",
    "title": "Pure Body Cream",
    "price": 25.4,
    "rating": 5.0,
    "description": "Pure Body Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/pure-body-cream-hand-foot/800/800",
    "brand": "The Ordinary",
    "category": "body",
    "subcategory": "hand-foot",
    "stock": 71,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-213",
    "title": "Velvet Perfume Oil",
    "price": 101.15,
    "rating": 4.9,
    "description": "Velvet Perfume Oil featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/velvet-perfume-oil-body-mist/800/800",
    "brand": "Fenty Beauty",
    "category": "fragrance",
    "subcategory": "body-mist",
    "stock": 113,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-214",
    "title": "Cloud Nail Polish",
    "price": 9.67,
    "rating": 4.1,
    "description": "Cloud Nail Polish featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/cloud-nail-polish-polish/800/800",
    "brand": "The Ordinary",
    "category": "nails",
    "subcategory": "polish",
    "stock": 30,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-215",
    "title": "Glow Brush Set",
    "price": 16.44,
    "rating": 4.8,
    "description": "Glow Brush Set featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/glow-brush-set-mirrors/800/800",
    "brand": "Huda Beauty",
    "category": "tools",
    "subcategory": "mirrors",
    "stock": 15,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-216",
    "title": "Dream Shaving Cream",
    "price": 27.28,
    "rating": 4.1,
    "description": "Dream Shaving Cream featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/dream-shaving-cream-shampoo/800/800",
    "brand": "Rare Beauty",
    "category": "men",
    "subcategory": "shampoo",
    "stock": 108,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-217",
    "title": "Shine Hair Care Set",
    "price": 75.19,
    "rating": 4.2,
    "description": "Shine Hair Care Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/shine-hair-care-set-skincare-set/800/800",
    "brand": "Schwarzkopf",
    "category": "gifts",
    "subcategory": "skincare-set",
    "stock": 55,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-218",
    "title": "Velvet Mascara",
    "price": 30.97,
    "rating": 4.2,
    "description": "Velvet Mascara featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/velvet-mascara-foundation/800/800",
    "brand": "CeraVe",
    "category": "makeup",
    "subcategory": "foundation",
    "stock": 70,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-219",
    "title": "Calm Face Mask",
    "price": 46.48,
    "rating": 4.3,
    "description": "Calm Face Mask featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/calm-face-mask-eye-cream/800/800",
    "brand": "CeraVe",
    "category": "skincare",
    "subcategory": "eye-cream",
    "stock": 105,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-220",
    "title": "Shine Hair Serum",
    "price": 12.25,
    "rating": 5.0,
    "description": "Shine Hair Serum featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/shine-hair-serum-spray/800/800",
    "brand": "MAC",
    "category": "hair",
    "subcategory": "spray",
    "stock": 35,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-221",
    "title": "Cloud Hand Cream",
    "price": 10.56,
    "rating": 4.4,
    "description": "Cloud Hand Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/cloud-hand-cream-sun-care/800/800",
    "brand": "Dior",
    "category": "body",
    "subcategory": "sun-care",
    "stock": 50,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-222",
    "title": "Brilliant Body Mist",
    "price": 105.02,
    "rating": 4.0,
    "description": "Brilliant Body Mist featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/brilliant-body-mist-gift-set/800/800",
    "brand": "GlowCart",
    "category": "fragrance",
    "subcategory": "gift-set",
    "stock": 68,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-223",
    "title": "Ultra Nail Care Kit",
    "price": 22.01,
    "rating": 4.6,
    "description": "Ultra Nail Care Kit featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/ultra-nail-care-kit-gel-acrylic/800/800",
    "brand": "TRESemm\u00e9",
    "category": "nails",
    "subcategory": "gel-acrylic",
    "stock": 43,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-224",
    "title": "Calm Hair Brush",
    "price": 48.95,
    "rating": 4.7,
    "description": "Calm Hair Brush featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/calm-hair-brush-bags/800/800",
    "brand": "Huda Beauty",
    "category": "tools",
    "subcategory": "bags",
    "stock": 14,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-225",
    "title": "Air Shaving Cream",
    "price": 54.06,
    "rating": 4.0,
    "description": "Air Shaving Cream featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/air-shaving-cream-shaving/800/800",
    "brand": "Maybelline",
    "category": "men",
    "subcategory": "shaving",
    "stock": 99,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-226",
    "title": "Ultra Makeup Gift Set",
    "price": 20.92,
    "rating": 4.8,
    "description": "Ultra Makeup Gift Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/ultra-makeup-gift-set-hair-set/800/800",
    "brand": "Fenty Beauty",
    "category": "gifts",
    "subcategory": "hair-set",
    "stock": 21,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-227",
    "title": "Luxe Primer",
    "price": 12.25,
    "rating": 4.9,
    "description": "Luxe Primer featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/luxe-primer-eyeliner/800/800",
    "brand": "Maybelline",
    "category": "makeup",
    "subcategory": "eyeliner",
    "stock": 91,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-228",
    "title": "Shine Eye Cream",
    "price": 44.46,
    "rating": 3.9,
    "description": "Shine Eye Cream featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/shine-eye-cream-sunscreen/800/800",
    "brand": "CeraVe",
    "category": "skincare",
    "subcategory": "sunscreen",
    "stock": 84,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-229",
    "title": "Fresh Hair Color",
    "price": 33.32,
    "rating": 4.1,
    "description": "Fresh Hair Color featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/fresh-hair-color-mask/800/800",
    "brand": "NYX",
    "category": "hair",
    "subcategory": "mask",
    "stock": 106,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-230",
    "title": "Revive Sunscreen",
    "price": 10.9,
    "rating": 4.5,
    "description": "Revive Sunscreen featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/revive-sunscreen-scrub/800/800",
    "brand": "CeraVe",
    "category": "body",
    "subcategory": "scrub",
    "stock": 83,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-231",
    "title": "Cloud Perfume Oil",
    "price": 86.22,
    "rating": 4.0,
    "description": "Cloud Perfume Oil featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/cloud-perfume-oil-unisex/800/800",
    "brand": "Sephora Collection",
    "category": "fragrance",
    "subcategory": "unisex",
    "stock": 113,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-232",
    "title": "Nourish Nail Care Kit",
    "price": 24.69,
    "rating": 4.3,
    "description": "Nourish Nail Care Kit featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/nourish-nail-care-kit-polish/800/800",
    "brand": "Maybelline",
    "category": "nails",
    "subcategory": "polish",
    "stock": 37,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-233",
    "title": "Hydra Makeup Bag",
    "price": 11.08,
    "rating": 4.2,
    "description": "Hydra Makeup Bag featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/hydra-makeup-bag-sponge/800/800",
    "brand": "NARS",
    "category": "tools",
    "subcategory": "sponge",
    "stock": 59,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-234",
    "title": "Dream Beard Oil",
    "price": 51.45,
    "rating": 5.0,
    "description": "Dream Beard Oil featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/dream-beard-oil-face-wash/800/800",
    "brand": "Huda Beauty",
    "category": "men",
    "subcategory": "face-wash",
    "stock": 77,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-235",
    "title": "Crystal Fragrance Box",
    "price": 25.86,
    "rating": 4.5,
    "description": "Crystal Fragrance Box featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/crystal-fragrance-box-hair-set/800/800",
    "brand": "TRESemm\u00e9",
    "category": "gifts",
    "subcategory": "hair-set",
    "stock": 95,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-236",
    "title": "Nourish Lipstick",
    "price": 19.58,
    "rating": 3.9,
    "description": "Nourish Lipstick featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/nourish-lipstick-highlighter/800/800",
    "brand": "TRESemm\u00e9",
    "category": "makeup",
    "subcategory": "highlighter",
    "stock": 10,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-237",
    "title": "Essential Face Mask",
    "price": 46.52,
    "rating": 4.9,
    "description": "Essential Face Mask featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/essential-face-mask-eye-cream/800/800",
    "brand": "Maybelline",
    "category": "skincare",
    "subcategory": "eye-cream",
    "stock": 68,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-238",
    "title": "Pure Hair Serum",
    "price": 8.42,
    "rating": 4.9,
    "description": "Pure Hair Serum featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/pure-hair-serum-oil/800/800",
    "brand": "Dior",
    "category": "hair",
    "subcategory": "oil",
    "stock": 46,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-239",
    "title": "Hydra Body Lotion",
    "price": 10.66,
    "rating": 4.9,
    "description": "Hydra Body Lotion featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/hydra-body-lotion-deodorant/800/800",
    "brand": "Pantene",
    "category": "body",
    "subcategory": "deodorant",
    "stock": 108,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-240",
    "title": "Nourish Eau de Parfum",
    "price": 93.96,
    "rating": 4.9,
    "description": "Nourish Eau de Parfum featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/nourish-eau-de-parfum-body-mist/800/800",
    "brand": "NYX",
    "category": "fragrance",
    "subcategory": "body-mist",
    "stock": 15,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-241",
    "title": "Shine Nail Polish",
    "price": 18.15,
    "rating": 4.2,
    "description": "Shine Nail Polish featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/shine-nail-polish-polish/800/800",
    "brand": "L'Oreal",
    "category": "nails",
    "subcategory": "polish",
    "stock": 46,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-242",
    "title": "Hydra Brush Set",
    "price": 44.22,
    "rating": 4.7,
    "description": "Hydra Brush Set featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/hydra-brush-set-sponge/800/800",
    "brand": "Fenty Beauty",
    "category": "tools",
    "subcategory": "sponge",
    "stock": 106,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-243",
    "title": "Studio Shaving Cream",
    "price": 52.15,
    "rating": 4.9,
    "description": "Studio Shaving Cream featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/studio-shaving-cream-perfume/800/800",
    "brand": "Pantene",
    "category": "men",
    "subcategory": "perfume",
    "stock": 12,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-244",
    "title": "Calm Hair Care Set",
    "price": 81.0,
    "rating": 4.9,
    "description": "Calm Hair Care Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/calm-hair-care-set-makeup-set/800/800",
    "brand": "Sephora Collection",
    "category": "gifts",
    "subcategory": "makeup-set",
    "stock": 106,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-245",
    "title": "Hydra Primer",
    "price": 31.47,
    "rating": 4.2,
    "description": "Hydra Primer featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/hydra-primer-setting/800/800",
    "brand": "NYX",
    "category": "makeup",
    "subcategory": "setting",
    "stock": 61,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-246",
    "title": "Nourish Face Oil",
    "price": 31.09,
    "rating": 4.1,
    "description": "Nourish Face Oil featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/nourish-face-oil-face-oil/800/800",
    "brand": "Huda Beauty",
    "category": "skincare",
    "subcategory": "face-oil",
    "stock": 15,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-247",
    "title": "Ultra Heat Protectant",
    "price": 38.38,
    "rating": 4.8,
    "description": "Ultra Heat Protectant featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/ultra-heat-protectant-mask/800/800",
    "brand": "Laneige",
    "category": "hair",
    "subcategory": "mask",
    "stock": 84,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-248",
    "title": "Radiant Body Cream",
    "price": 11.8,
    "rating": 4.7,
    "description": "Radiant Body Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/radiant-body-cream-wash/800/800",
    "brand": "CeraVe",
    "category": "body",
    "subcategory": "wash",
    "stock": 49,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-249",
    "title": "Silky Body Mist",
    "price": 76.03,
    "rating": 4.4,
    "description": "Silky Body Mist featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/silky-body-mist-gift-set/800/800",
    "brand": "Dior",
    "category": "fragrance",
    "subcategory": "gift-set",
    "stock": 67,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-250",
    "title": "Velvet Nail Polish",
    "price": 19.16,
    "rating": 4.2,
    "description": "Velvet Nail Polish featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/velvet-nail-polish-polish/800/800",
    "brand": "GlowCart",
    "category": "nails",
    "subcategory": "polish",
    "stock": 57,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-251",
    "title": "Dream LED Mirror",
    "price": 46.34,
    "rating": 5.0,
    "description": "Dream LED Mirror featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/dream-led-mirror-bags/800/800",
    "brand": "Pantene",
    "category": "tools",
    "subcategory": "bags",
    "stock": 82,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-252",
    "title": "Air Men's Perfume",
    "price": 25.45,
    "rating": 4.8,
    "description": "Air Men's Perfume featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/air-mens-perfume-face-wash/800/800",
    "brand": "Maybelline",
    "category": "men",
    "subcategory": "face-wash",
    "stock": 6,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-253",
    "title": "Perfect Hair Care Set",
    "price": 87.32,
    "rating": 4.2,
    "description": "Perfect Hair Care Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/perfect-hair-care-set-skincare-set/800/800",
    "brand": "Laneige",
    "category": "gifts",
    "subcategory": "skincare-set",
    "stock": 5,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-254",
    "title": "Pure Mascara",
    "price": 26.74,
    "rating": 4.8,
    "description": "Pure Mascara featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/pure-mascara-highlighter/800/800",
    "brand": "GlowCart",
    "category": "makeup",
    "subcategory": "highlighter",
    "stock": 102,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-255",
    "title": "Soft Serum",
    "price": 33.82,
    "rating": 4.8,
    "description": "Soft Serum featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/soft-serum-moisturizer/800/800",
    "brand": "TRESemm\u00e9",
    "category": "skincare",
    "subcategory": "moisturizer",
    "stock": 82,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-256",
    "title": "Shine Hair Mask",
    "price": 39.31,
    "rating": 4.0,
    "description": "Shine Hair Mask featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/shine-hair-mask-oil/800/800",
    "brand": "Fenty Beauty",
    "category": "hair",
    "subcategory": "oil",
    "stock": 79,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-257",
    "title": "Air Body Scrub",
    "price": 25.13,
    "rating": 4.7,
    "description": "Air Body Scrub featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/air-body-scrub-cream/800/800",
    "brand": "Laneige",
    "category": "body",
    "subcategory": "cream",
    "stock": 44,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-258",
    "title": "Essential Body Mist",
    "price": 74.25,
    "rating": 4.1,
    "description": "Essential Body Mist featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/essential-body-mist-women/800/800",
    "brand": "The Ordinary",
    "category": "fragrance",
    "subcategory": "women",
    "stock": 105,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-259",
    "title": "Cloud Nail Care Kit",
    "price": 11.65,
    "rating": 4.8,
    "description": "Cloud Nail Care Kit featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/cloud-nail-care-kit-gel-acrylic/800/800",
    "brand": "NARS",
    "category": "nails",
    "subcategory": "gel-acrylic",
    "stock": 58,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-260",
    "title": "Radiant Lash Curler",
    "price": 43.83,
    "rating": 4.3,
    "description": "Radiant Lash Curler featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/radiant-lash-curler-hair-brush/800/800",
    "brand": "Kiehl's",
    "category": "tools",
    "subcategory": "hair-brush",
    "stock": 17,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-261",
    "title": "Fresh Shaving Cream",
    "price": 28.89,
    "rating": 4.8,
    "description": "Fresh Shaving Cream featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/fresh-shaving-cream-face-wash/800/800",
    "brand": "Kiehl's",
    "category": "men",
    "subcategory": "face-wash",
    "stock": 109,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-262",
    "title": "Essential Makeup Gift Set",
    "price": 21.35,
    "rating": 4.3,
    "description": "Essential Makeup Gift Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/essential-makeup-gift-set-makeup-set/800/800",
    "brand": "Maybelline",
    "category": "gifts",
    "subcategory": "makeup-set",
    "stock": 106,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-263",
    "title": "Radiant Lipstick",
    "price": 27.19,
    "rating": 4.0,
    "description": "Radiant Lipstick featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/radiant-lipstick-bronzer/800/800",
    "brand": "MAC",
    "category": "makeup",
    "subcategory": "bronzer",
    "stock": 109,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-264",
    "title": "Radiant Face Mask",
    "price": 21.36,
    "rating": 4.7,
    "description": "Radiant Face Mask featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/radiant-face-mask-moisturizer/800/800",
    "brand": "GlowCart",
    "category": "skincare",
    "subcategory": "moisturizer",
    "stock": 52,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-265",
    "title": "Pro Hair Color",
    "price": 13.15,
    "rating": 4.7,
    "description": "Pro Hair Color featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/pro-hair-color-color/800/800",
    "brand": "Schwarzkopf",
    "category": "hair",
    "subcategory": "color",
    "stock": 11,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-266",
    "title": "Air Body Wash",
    "price": 16.85,
    "rating": 4.2,
    "description": "Air Body Wash featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/air-body-wash-hand-foot/800/800",
    "brand": "Dior",
    "category": "body",
    "subcategory": "hand-foot",
    "stock": 23,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-267",
    "title": "Ultra Body Mist",
    "price": 70.1,
    "rating": 4.3,
    "description": "Ultra Body Mist featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/ultra-body-mist-unisex/800/800",
    "brand": "GlowCart",
    "category": "fragrance",
    "subcategory": "unisex",
    "stock": 15,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-268",
    "title": "Soft UV Gel Kit",
    "price": 16.07,
    "rating": 4.3,
    "description": "Soft UV Gel Kit featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/soft-uv-gel-kit-polish/800/800",
    "brand": "Kiehl's",
    "category": "nails",
    "subcategory": "polish",
    "stock": 117,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-269",
    "title": "Silky Lash Curler",
    "price": 14.92,
    "rating": 4.7,
    "description": "Silky Lash Curler featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/silky-lash-curler-brushes/800/800",
    "brand": "Dior",
    "category": "tools",
    "subcategory": "brushes",
    "stock": 51,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-270",
    "title": "Fresh Beard Oil",
    "price": 20.6,
    "rating": 4.7,
    "description": "Fresh Beard Oil featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/fresh-beard-oil-face-wash/800/800",
    "brand": "CeraVe",
    "category": "men",
    "subcategory": "face-wash",
    "stock": 17,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-271",
    "title": "Luxe Makeup Gift Set",
    "price": 82.7,
    "rating": 5.0,
    "description": "Luxe Makeup Gift Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/luxe-makeup-gift-set-skincare-set/800/800",
    "brand": "Garnier",
    "category": "gifts",
    "subcategory": "skincare-set",
    "stock": 30,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-272",
    "title": "Studio Eyeshadow Palette",
    "price": 15.06,
    "rating": 4.9,
    "description": "Studio Eyeshadow Palette featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/studio-eyeshadow-palette-foundation/800/800",
    "brand": "Kiehl's",
    "category": "makeup",
    "subcategory": "foundation",
    "stock": 45,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-273",
    "title": "Velvet Face Mask",
    "price": 27.09,
    "rating": 3.9,
    "description": "Velvet Face Mask featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/velvet-face-mask-toner/800/800",
    "brand": "NYX",
    "category": "skincare",
    "subcategory": "toner",
    "stock": 17,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-274",
    "title": "Shine Hair Oil",
    "price": 20.73,
    "rating": 4.2,
    "description": "Shine Hair Oil featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/shine-hair-oil-oil/800/800",
    "brand": "The Ordinary",
    "category": "hair",
    "subcategory": "oil",
    "stock": 115,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-275",
    "title": "Luxe Body Cream",
    "price": 18.37,
    "rating": 4.4,
    "description": "Luxe Body Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/luxe-body-cream-deodorant/800/800",
    "brand": "GlowCart",
    "category": "body",
    "subcategory": "deodorant",
    "stock": 50,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-276",
    "title": "Cloud Gift Set",
    "price": 28.79,
    "rating": 4.7,
    "description": "Cloud Gift Set featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/cloud-gift-set-gift-set/800/800",
    "brand": "Olaplex",
    "category": "fragrance",
    "subcategory": "gift-set",
    "stock": 22,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-277",
    "title": "Calm Nail Polish",
    "price": 15.91,
    "rating": 4.3,
    "description": "Calm Nail Polish featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/calm-nail-polish-tools/800/800",
    "brand": "Laneige",
    "category": "nails",
    "subcategory": "tools",
    "stock": 66,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-278",
    "title": "Radiant Brush Set",
    "price": 39.96,
    "rating": 4.9,
    "description": "Radiant Brush Set featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/radiant-brush-set-tweezers/800/800",
    "brand": "NARS",
    "category": "tools",
    "subcategory": "tweezers",
    "stock": 71,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-279",
    "title": "Calm Men's Perfume",
    "price": 54.0,
    "rating": 4.4,
    "description": "Calm Men's Perfume featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/calm-mens-perfume-shampoo/800/800",
    "brand": "L'Oreal",
    "category": "men",
    "subcategory": "shampoo",
    "stock": 76,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-280",
    "title": "Silky Makeup Gift Set",
    "price": 51.77,
    "rating": 4.5,
    "description": "Silky Makeup Gift Set featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/silky-makeup-gift-set-fragrance-box/800/800",
    "brand": "Pantene",
    "category": "gifts",
    "subcategory": "fragrance-box",
    "stock": 105,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-281",
    "title": "Cloud Mascara",
    "price": 32.38,
    "rating": 4.0,
    "description": "Cloud Mascara featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/cloud-mascara-primer/800/800",
    "brand": "GlowCart",
    "category": "makeup",
    "subcategory": "primer",
    "stock": 58,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-282",
    "title": "Brilliant Cleanser",
    "price": 20.28,
    "rating": 4.0,
    "description": "Brilliant Cleanser featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/brilliant-cleanser-face-oil/800/800",
    "brand": "Sephora Collection",
    "category": "skincare",
    "subcategory": "face-oil",
    "stock": 43,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-283",
    "title": "Hydra Hair Serum",
    "price": 21.3,
    "rating": 4.4,
    "description": "Hydra Hair Serum featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/hydra-hair-serum-mask/800/800",
    "brand": "Sephora Collection",
    "category": "hair",
    "subcategory": "mask",
    "stock": 22,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-284",
    "title": "Silky Deodorant",
    "price": 9.03,
    "rating": 4.0,
    "description": "Silky Deodorant featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/silky-deodorant-scrub/800/800",
    "brand": "Huda Beauty",
    "category": "body",
    "subcategory": "scrub",
    "stock": 104,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-285",
    "title": "Nourish Body Mist",
    "price": 42.31,
    "rating": 4.2,
    "description": "Nourish Body Mist featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/nourish-body-mist-women/800/800",
    "brand": "Pantene",
    "category": "fragrance",
    "subcategory": "women",
    "stock": 19,
    "isHot": false,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-286",
    "title": "Calm Nail Polish",
    "price": 21.33,
    "rating": 4.1,
    "description": "Calm Nail Polish featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/calm-nail-polish-polish/800/800",
    "brand": "Laneige",
    "category": "nails",
    "subcategory": "polish",
    "stock": 87,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-287",
    "title": "Revive Brush Set",
    "price": 30.53,
    "rating": 4.8,
    "description": "Revive Brush Set featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/revive-brush-set-hair-brush/800/800",
    "brand": "GlowCart",
    "category": "tools",
    "subcategory": "hair-brush",
    "stock": 116,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-288",
    "title": "Glow Men's Perfume",
    "price": 16.23,
    "rating": 4.3,
    "description": "Glow Men's Perfume featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/glow-mens-perfume-perfume/800/800",
    "brand": "Pantene",
    "category": "men",
    "subcategory": "perfume",
    "stock": 70,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-289",
    "title": "Luxe Fragrance Box",
    "price": 29.07,
    "rating": 4.5,
    "description": "Luxe Fragrance Box featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/luxe-fragrance-box-skincare-set/800/800",
    "brand": "Sephora Collection",
    "category": "gifts",
    "subcategory": "skincare-set",
    "stock": 5,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-290",
    "title": "Luxe Mascara",
    "price": 32.57,
    "rating": 4.5,
    "description": "Luxe Mascara featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/luxe-mascara-highlighter/800/800",
    "brand": "Sephora Collection",
    "category": "makeup",
    "subcategory": "highlighter",
    "stock": 115,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-291",
    "title": "Luxe Eye Cream",
    "price": 37.38,
    "rating": 4.9,
    "description": "Luxe Eye Cream featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/luxe-eye-cream-exfoliator/800/800",
    "brand": "Schwarzkopf",
    "category": "skincare",
    "subcategory": "exfoliator",
    "stock": 11,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-292",
    "title": "Glow Heat Protectant",
    "price": 37.88,
    "rating": 5.0,
    "description": "Glow Heat Protectant featuring salon-grade formula that strengthens and adds healthy shine.",
    "image": "https://picsum.photos/seed/glow-heat-protectant-heat-protectant/800/800",
    "brand": "NARS",
    "category": "hair",
    "subcategory": "heat-protectant",
    "stock": 35,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-293",
    "title": "Radiant Foot Cream",
    "price": 16.4,
    "rating": 4.9,
    "description": "Radiant Foot Cream featuring lightweight, fast-absorbing texture for silky-smooth skin.",
    "image": "https://picsum.photos/seed/radiant-foot-cream-lotion/800/800",
    "brand": "The Ordinary",
    "category": "body",
    "subcategory": "lotion",
    "stock": 27,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-294",
    "title": "Prime Perfume Oil",
    "price": 50.41,
    "rating": 3.9,
    "description": "Prime Perfume Oil featuring signature notes crafted for an unforgettable trail.",
    "image": "https://picsum.photos/seed/prime-perfume-oil-men/800/800",
    "brand": "The Ordinary",
    "category": "fragrance",
    "subcategory": "men",
    "stock": 102,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-295",
    "title": "Prime Cuticle Oil",
    "price": 23.32,
    "rating": 4.3,
    "description": "Prime Cuticle Oil featuring chip-resistant wear with ultra-glossy shine.",
    "image": "https://picsum.photos/seed/prime-cuticle-oil-tools/800/800",
    "brand": "Sephora Collection",
    "category": "nails",
    "subcategory": "tools",
    "stock": 94,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-296",
    "title": "Studio LED Mirror",
    "price": 11.98,
    "rating": 4.7,
    "description": "Studio LED Mirror featuring ergonomic design built for precision and ease.",
    "image": "https://picsum.photos/seed/studio-led-mirror-hair-brush/800/800",
    "brand": "NARS",
    "category": "tools",
    "subcategory": "hair-brush",
    "stock": 86,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-297",
    "title": "Radiant Shaving Cream",
    "price": 47.5,
    "rating": 4.1,
    "description": "Radiant Shaving Cream featuring clean, effective performance tailored for daily use.",
    "image": "https://picsum.photos/seed/radiant-shaving-cream-aftershave/800/800",
    "brand": "CeraVe",
    "category": "men",
    "subcategory": "aftershave",
    "stock": 83,
    "isHot": true,
    "isNew": true,
    "discount": 0
  },
  {
    "id": "p-298",
    "title": "Crystal Fragrance Box",
    "price": 82.11,
    "rating": 4.8,
    "description": "Crystal Fragrance Box featuring curated favorites in a ready-to-gift box.",
    "image": "https://picsum.photos/seed/crystal-fragrance-box-makeup-set/800/800",
    "brand": "L'Oreal",
    "category": "gifts",
    "subcategory": "makeup-set",
    "stock": 108,
    "isHot": true,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-299",
    "title": "Prime Highlighter",
    "price": 31.74,
    "rating": 4.6,
    "description": "Prime Highlighter featuring long-wear, blendable pigments and a comfortable finish.",
    "image": "https://picsum.photos/seed/prime-highlighter-eyeliner/800/800",
    "brand": "Huda Beauty",
    "category": "makeup",
    "subcategory": "eyeliner",
    "stock": 80,
    "isHot": false,
    "isNew": false,
    "discount": 0
  },
  {
    "id": "p-300",
    "title": "Air Moisturizer",
    "price": 35.1,
    "rating": 5.0,
    "description": "Air Moisturizer featuring dermatologist-tested actives for visible results with gentle care.",
    "image": "https://picsum.photos/seed/air-moisturizer-serum/800/800",
    "brand": "Dior",
    "category": "skincare",
    "subcategory": "serum",
    "stock": 89,
    "isHot": false,
    "isNew": false,
    "discount": 0
  }
];
